# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-29 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
